; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

; ------------ DATA STORAGE INITIALIZATION -------------

; File Paths for Python program/input/output
py_prog_path := "backend_cli.py"
py_out_path := "backend_cli.output"
ahk_out_path := "backend_cli.input"

; Valid currency BaseTypes
curr_valid := ["Exalted Orb", "Orb of Alteration", "Blessed Orb", "Blacksmith's Whetstone"
    , "Armourer's Scrap", "Glassblower's Bauble", "Orb of Transmutation", "Orb of Augmentation"
    , "Chromatic Orb", "Jeweller's Orb", "Orb of Chance", "Orb of Alchemy", "Orb of Binding"
    , "Orb of Fusing", "Vaal Orb", "Orb of Horizons", "Cartographer's Chisel", "Regal Orb"
    , "Orb of Regret", "Orb of Scouring" , "Gemcutter's Prism"]
validstr := ""
for idx, val in curr_valid
    validstr .= "|" val

; Valid rare item slots
rare_valid := ["WeaponsX", "Weapons3", "Body Armours", "Helmets", "Gloves", "Boots", "Amulets"
    , "Rings", "Belts"]
validstr2 := ""
for idx,val in rare_valid
    validstr2 .= "|" val

; Coloring for rares by slot (copied from consts.py)
rare_colors := {"Weapons" : "c80000", "Body Armours" : "ff00ff", "Helmets" : "ff7200"
    , "Gloves" : "ffe400", "Boots" : "00ff00", "Amulets" : "00ffff", "Rings" : "4100bd"
    , "Belts" : "0000c8"}

; Flask BaseTypes and show flags
flasks := {"Divine Life Flask" : [0, 0], "Eternal Mana Flask" : [0, 0]
    , "Quicksilver Flask" : [0, 0], "Bismuth Flask" : [0, 0], "Amethyst Flask" : [0, 0]
    , "Ruby Flask" : [0, 0], "Sapphire Flask" : [0, 0], "Topaz Flask" : [0, 0]
    , "Aquamarine Flask" : [0, 0], "Diamond Flask" : [0, 0], "Jade Flask" : [0, 0]
    , "Quartz Flask" : [0, 0], "Granite Flask" : [0, 0], "Sulphur Flask" : [0, 0]
    , "Basalt Flask" : [0, 0], "Silver Flask" : [0, 0], "Stibnite Flask" : [0, 0]
    , "Corundum Flask" : [0, 0], "Gold Flask" : [0, 0]}

; RGB size tooltips
rgbtooltip := {"none" : "Hide everything", "small" : "2x2, 4x1, and 3x1"
    , "medium" : "3x2, 2x2, 4x1, and 3x1", "large" : "Show everything"}
rgbmap := {"none" : 1, "small" : 2, "medium" : 3, "large" : 4}

; Oil names, ordered from highest to lowest value
oils := ["Tainted", "Golden", "Silver", "Opalescent", "Black", "Crimson", "Violet", "Indigo"
    , "Azure", "Teal", "Verdant", "Amber", "Sepia", "Clear"]

; Currency stack size options
cstack_input_dict := {1:1, 2:2, 4:3, 100:4}
cstack_input_dict_low := {1:1, 2:2, 4:3, 6:4, 100:5}
cstack_options := ["1+", "2+", "4+", "6+", "None"]
cstack_values := [5, 5, 5, 5, 5, 5, 5, 5, 5]
cstack_values_base := [5, 5, 5, 5, 5, 5, 5, 5, 5]
options_idx := 1

; Flask ilvl options
flvl_options := ["None", "All", "84+"]

; Scroll stack sizes
base_portstack := 5
base_wisstack := 5
portal_stack := 5
wisdom_stack := 5

; -------------- DATA LOADING -------------------------------
; Read starting filter data from python client
; REWRITE --------------------------------
curr_txt := []
curr_ids := []
curr_val := []
curr_val_start := []
rare_txt := []
rare_ids := []
rare_val := []
rare_val_start := []
; REWRITE ---------------------------
all_currency := ""
rare_dict := {"Weapons" : 1, "Body Armours" : 1, "Helmets" : 1, "Gloves" : 1, "Boots" : 1, "Amulets" : 1, "Rings" : 1, "Belts" : 1}
fake_queue := []
profiles := []
FileDelete, %ahk_out_path%
RunWait, python %py_prog_path% get_all_profile_names, , Hide
FileRead, py_out_text, %py_out_path%
Loop, parse, py_out_text, `n, `r
{
    if(A_LoopField = "")
        continue
    profiles.push(A_LoopField)
}
active_profile := profiles[1]

; Build batch file to get all info
FileAppend, get_all_currency_tiers`nget_all_chaos_recipe_statuses`nget_hide_maps_below_tier`nget_currency_tier_min_visible_stack_size tportal`nget_currency_tier_min_visible_stack_size twisdom`nget_hide_essences_above_tier`nget_hide_unique_items_above_tier`nget_gem_min_quality`nget_rgb_item_max_size`nget_flask_min_quality`nget_lowest_visible_oil`n, %ahk_out_path%
Loop, 9
{
    FileAppend, get_currency_tier_min_visible_stack_size %A_Index%`n, %ahk_out_path%
}
for key in flasks
{
    FileAppend, get_flask_visibility "%key%"`r`n, %ahk_out_path% 
    fake_queue.Push(key)
}

; Run batch
RunWait, python %py_prog_path% run_batch %active_profile%, , Hide
FileRead, py_out_text, %py_out_path%

; Parse batch output
prog := 0
Loop, parse, py_out_text, `n, `r
{
    if(A_LoopField = "")
        continue
    if(InStr(A_LoopField, "@"))
    {
        line := 0
        prog := prog + 1
        continue
    }
    Switch prog
    {
    Case 0:
        splits := StrSplit(A_LoopField, ";")
        ;if(InStr(validstr, splits[1])){
        curr_txt.Push(splits[1])
        curr_val.Push(splits[2])
        curr_val_start.Push(splits[2])
        all_currency .= splits[1] "|"
        ;}
    Case 1:
        splits := StrSplit(A_LoopField, ";")
        if(InStr(validstr2, splits[1]))
        {
            rare_txt.Push(splits[1])
            rare_val.Push(splits[2])
            rare_val_start.Push(splits[2])
        }
        rare_dict[splits[1]] := splits[2]
    Case 2:
        maphide := A_LoopField
    Case 3:
        portal_stack := cstack_input_dict_low[A_LoopField]
        base_portstack := portal_stack
    Case 4:
        wisdom_stack := cstack_input_dict_low[A_LoopField]
        base_wisstack := wisdom_stack
    ;Case 5: --- DEPRICATED, REPLACE WITH ESS? -----
    ;    currhide := A_LoopField
    Case 5:
        esshide := A_LoopField
    Case 6:
        uniqhide := A_LoopField
    Case 7:
        gemmin := A_LoopField
        base_gemmin := gemmin
    Case 8:
        rgbsize := A_LoopField
        base_rgbsize := rgbsize
    Case 9:
        flaskmin := A_LoopField
        base_flaskmin := flaskmin
    Case 10:
        oil_text := StrSplit(A_LoopField, " ")
        min_oil := -1
        for idx, val in oils 
        {
            if (val = oil_text[1])
                min_oil := idx
        }
        base_min_oil := min_oil
    Case 11, 12, 13, 14, 15, 16, 17:
        cstack_values[prog-10] := cstack_input_dict[A_LoopField]
        cstack_values_base[prog-10] := cstack_input_dict[A_LoopField]
    Case 18, 19:
        cstack_values[prog-10] := cstack_input_dict_low[A_LoopField]
        cstack_values_base[prog-10] := cstack_input_dict_low[A_LoopField]
    Default:
        splits := StrSplit(A_LoopField, " ")
        if (splits[1] = 1)
        {
            flasks[fake_queue[prog - 19]] := [1,1]
        }
        else if (splits[2] = 1)
        {
            flasks[fake_queue[prog - 19]] := [2,2]
        }
        else
        {
            flasks[fake_queue[prog - 19]] := [0,0]
        }
    }
}



; ----------- GUI CREATION / REBUILD -------------------

GuiBuild:
Gui Color, 0x111122, 0x111133

Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s16 Bold
Gui Add, Text, x192 y8 w556 h26 +0x200 +Center, PoE Dynamic Loot Filter
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s10 Bold
; ---- CURRENCY DATA ----
currtexts := ["", "", "", "", "", "", "", "", ""]
For idx in curr_txt {
    currtexts[curr_val[idx]] .= curr_txt[idx] "|"
}
Loop, 9 {
    currtexts[A_Index] := RegExReplace( currtexts[A_Index], "\|$" )
}
cstacktext := ""
cstacktext_less := ""
Loop, 5 {
    cstacktext .= cstack_options[A_Index] "|"
    if (A_Index != 4) {
        cstacktext_less .= cstack_options[A_Index] "|"
    }
}
cstacktext := RegExReplace( cstacktext, "\|$" )
cstacktext_less := RegExReplace( cstacktext_less, "\|$" )
; ---- CURRENCY GUI -----
Gui Add, GroupBox, x16 y48 w483 h783, Currency
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, Text, x32 y168 w115 h28 +0x200, T1 Stack Size:
Gui Add, DropDownList, % "vValueCurrencyDdlT1 gHandleCurrencyDdlEvent x120 y168 w46 Choose"cstack_values[1],  %cstacktext_less%
Gui Font
Gui Font, c0x00e8b2 s10
Gui Add, ListBox, x32 y192 w135 h164 +Sort, % currtexts[1]
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, Text, x16 y368 w469 h1 +0x10
Gui Add, Text, x208 y48 w0 h364 +0x10
Gui Add, Text, x176 y166 w5 h614 +0x1 +0x10
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, Text, x192 y168 w115 h28 +0x200, T2 Stack Size:
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, DropDownList,% "vValueCurrencyDdlT2 gHandleCurrencyDdlEvent x280 y168 w46 Choose"cstack_values[2], %cstacktext_less%
Gui Font, c0x00e8b2 s10
Gui Add, ListBox, x192 y192 w135 h164 +Sort, % currtexts[2]
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, Text, x336 y170 w2 h607 +0x1 +0x10
Gui Add, Text, x352 y168 w115 h28 +0x200, T3 Stack Size:
Gui Add, DropDownList,% "vValueCurrencyDdlT3 gHandleCurrencyDdlEvent x440 y168 w48 Choose"cstack_values[3], %cstacktext_less%
Gui Font
Gui Font, c0x00e8b2 s10
Gui Add, ListBox, x352 y192 w135 h164 +Sort, % currtexts[3]
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, Text, x32 y376 w115 h28 +0x200, T4 Stack Size:
Gui Add, Text, x192 y376 w115 h28 +0x200, T5 Stack Size:
Gui Add, Text, x352 y376 w115 h28 +0x200, T6 Stack Size:
Gui Font
Gui Font, c0x00e8b2 s10
Gui Add, ListBox, x32 y400 w135 h164 +Sort, % currtexts[4]
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s10
Gui Add, ListBox, x192 y400 w135 h164 +Sort, % currtexts[5]
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s10
Gui Add, ListBox, x352 y400 w135 h164 +Sort, % currtexts[6]
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, Text, x16 y576 w468 h1 +0x10
Gui Add, Text, x32 y584 w115 h28 +0x200, T7 Stack Size:
Gui Add, Text, x192 y584 w115 h28 +0x200, T8 Stack Size:
Gui Add, Text, x352 y584 w115 h28 +0x200, T9 Stack Size:
Gui Font
Gui Font, c0x00e8b2 s10
Gui Add, ListBox, x32 y608 w135 h164 +Sort, % currtexts[7]
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s10
Gui Add, ListBox, x192 y608 w135 h164 +Sort, % currtexts[8]
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s10
Gui Add, ListBox, x352 y608 w135 h164 +Sort, % currtexts[9]
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, Text, x16 y784 w468 h2 +0x10
Gui Add, Text, x56 y792 w115 h28 +0x200, Portal Stack Size:
Gui Add, DropDownList, vValueCurrencyDdlTportal gHandleCurrencyDdlEvent Choose%portal_stack% x176 y792 w48, % cstacktext
Gui Add, Text, x256 y792 w5 h35 +0x1 +0x10
Gui Add, Text, x288 y792 w133 h28 +0x200, Wisdom Stack Size:
Gui Add, DropDownList, vValueCurrencyDdlTwisdom gHandleCurrencyDdlEvent Choose%wisdom_stack% x424 y792 w48, % cstacktext

; -------- END CURRENCY ------------------
; -------- CHAOS RARES -------------------

Gui Font
Gui Font, c0x00e8b2 s10 Bold
Gui Add, GroupBox, x528 y48 w285 h169, Chaos Recipe Rares
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s14, Segoe UI
Gui Add, CheckBox,% "x544 y80 w123 h26" (rare_dict["Weapons"]? " Checked" : ""), Weapons
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s14, Segoe UI
Gui Add, CheckBox,% "x544 y112 w123 h26" (rare_dict["Body Armours"]? " Checked" : ""), Armours
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s14, Segoe UI
Gui Add, CheckBox,% "x544 y176 w123 h26" (rare_dict["Gloves"]? " Checked" : ""), Gloves
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s14, Segoe UI
Gui Add, CheckBox,% "x544 y144 w123 h26" (rare_dict["Helmets"]? " Checked" : ""), Helmets
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s14, Segoe UI
Gui Add, CheckBox,% "x680 y80 w123 h26" (rare_dict["Boots"]? " Checked" : ""), Boots
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s14, Segoe UI
Gui Add, CheckBox,% "x680 y112 w123 h26" (rare_dict["Belts"]? " Checked" : ""), Belts
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s14, Segoe UI
Gui Add, CheckBox,% "x680 y144 w123 h26" (rare_dict["Rings"]? " Checked" : ""), Rings
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s14, Segoe UI
Gui Add, CheckBox,% "x680 y176 w123 h26" (rare_dict["Amulets"]? " Checked" : ""), Amulets

; ----------- END RARES -----------
; ------------ PROFILES -----------

for key, val in profiles
    ProfString .= val "|"
RTrim(ProfString, "|")

Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s12 Bold, Segoe UI
Gui Add, Text, x880 y8 w61 h29 +0x200, Profile:
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, DropDownList, x936 y8 w151 Choose1, %ProfString%
Gui Add, Button, x1112 y32 w56 h0, &OK
Gui Font
Gui Font, c0x00e8b2 s12 Bold, Segoe UI
Gui Add, Button, x1088 y8 w30 h30, +
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, Text, x24 y160 w467 h1 +0x10

; ---------- END PROFILE ------------
; ---------- MORE CURRENCY? ---------
Gui Font
Gui Font, c0x00e8b2 s10 Bold, Segoe UI
Gui Add, Text, x32 y120 w148 h28 +0x200 +Right, Move Currency to Tier:
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, DropDownList, x184 y120 w191, %all_currency%
Gui Font
Gui Font, c0x00e8b2 s10 Bold, Segoe UI
Gui Add, Text, x384 y120 w16 h28 +0x200, ➔
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, DropDownList, x408 y120 w41, T1|T2|T3|T4|T5|T6|T7|T8|T9

; ---------- END CURR 2 ------------
; ---------- META BUTTONS ----------
Gui Font
Gui Font, c0x00e8b2 s10 Bold, Segoe UI
Gui Add, Button, x456 y120 w32 h30, Go
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s11 Bold, Segoe UI
Gui Add, Button, x872 y752 w224 h31, &Write Filter && Close UI
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s11 Bold, Segoe UI
Gui Add, Button, x872 y712 w226 h32, (Re)&Import Filter

; ---------- END META BUTTONS -------
; --------- MISC --------------------

Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s10 Bold
Gui Add, GroupBox, x840 y56 w288 h74, Regular Maps
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, Text, x856 y88 w152 h28 +0x200, Hide Maps Below Tier:
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
; -------- FLASKS -------------------
flask_avail := ""
flask_high := ""
flask_low := ""
for flask, arr in flasks
{
    if (arr[1] == 1)
        flask_high .= flask "|"
    else if (arr[2] == 1)
        flask_low .= flask "|"
    else
        flask_avail .= flask "|"
}
RTrim(flask_avail, "|")
RTrim(flask_high, "|")
RTrim(flask_low, "|")
Gui Font
Gui Font, c0x00e8b2 s10 Bold
Gui Add, GroupBox, x528 y232 w286 h417, Flask BaseTypes
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, ListBox, x544 y296 w257 h104 +Sort, %flask_low%
Gui Font
Gui Font, c0x00e8b2 s11 Norm, Segoe UI
Gui Add, Text, x544 y264 w101 h28 +0x200, Any ItemLevel:
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, DropDownList, x648 y264 w153, Add...||%flask_avail%
Gui Add, Button, x592 y408 w144 h31, Remove Selected
Gui Add, Text, x528 y400 w276 h0 +0x10
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, Text, x544 y464 w108 h28 +0x200, High ItemLevel:
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, Text, x536 y448 w266 h2 +0x10
Gui Add, DropDownList, x648 y464 w153, Add...||%flask_avail%
Gui Add, ListBox, x544 y496 w257 h104 +Sort, %flask_high%
Gui Add, Button, x592 y608 w144 h31, Remove Selected
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, Text, x544 y696 w120 h28 +0x200, Gem Min Quality:
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, Text, x544 y736 w120 h28 +0x200, Flask Min Quality:
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, Text, x544 y776 w136 h28 +0x200, RGB Max Item Size: 
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, DropDownList,% "x680 y776 w113 Choose" rgbmap[rgbsize], Hide All|Small|Medium|Large
Gui Font
Gui Font, c0x00e8b2 s10 Bold
Gui Add, GroupBox, x840 y144 w288 h234, Tier Visibility
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s11 Norm, Segoe UI
Gui Add, Text, x856 y176 w179 h28 +0x200, Hide Essences Above Tier:
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, DropDownList, x1032 y176 w33, 1|2|3|4||5
Gui Font
Gui Font, c0x00e8b2 s11 Norm, Segoe UI
Gui Add, Text, x856 y216 w185 h28 +0x200, Hide Div Cards Above Tier:
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, DropDownList, x1040 y216 w33, 1|2|3|4||5
Gui Font
Gui Font, c0x00e8b2 s11 Norm, Segoe UI
Gui Add, Text, x856 y256 w203 h28 +0x200, Hide Unique Items Above Tier:
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s11 Norm, Segoe UI
Gui Add, Text, x856 y296 w206 h28 +0x200, Hide Unique Maps Above Tier:
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s11 Norm, Segoe UI
Gui Add, Text, x856 y336 w113 h28 +0x200, Hide Oils Below:
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, DropDownList, x1064 y256 w33, 1|2|3|4||5
Gui Add, DropDownList, x1064 y296 w33, 1|2|3|4||5
; ------------- OILS -----------------------
oilstr := ""
for key, val in oils {
    oilstr .= val "|"
}
RTrim(oilstr, "|")
Gui Add, DropDownList, x968 y336 w130 Choose%min_oil%, %oilstr%
Gui Font
Gui Font, c0x00e8b2 s10 Bold
Gui Add, GroupBox, x840 y680 w288 h116, Filter Actions
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, DropDownList,% "vValueCurrencyDdlT4 gHandleCurrencyDdlEvent x120 y376 w46 Choose"cstack_values[4], %cstacktext_less%
Gui Add, DropDownList,% "vValueCurrencyDdlT5 gHandleCurrencyDdlEvent x280 y376 w46 Choose"cstack_values[5], %cstacktext_less%
Gui Add, DropDownList,% "vValueCurrencyDdlT6 gHandleCurrencyDdlEvent x440 y376 w46 Choose"cstack_values[6], %cstacktext_less%
Gui Add, DropDownList,% "vValueCurrencyDdlT7 gHandleCurrencyDdlEvent x120 y584 w46 Choose"cstack_values[7], %cstacktext_less%
Gui Add, DropDownList,% "vValueCurrencyDdlT8 gHandleCurrencyDdlEvent x280 y584 w46 Choose"cstack_values[8], %cstacktext%
Gui Add, DropDownList,% "vValueCurrencyDdlT9 gHandleCurrencyDdlEvent x440 y584 w46 Choose"cstack_values[9], %cstacktext%
Gui Font
Gui Font, c0x00e8b2 s10 Bold, Segoe UI
Gui Add, Text, x32 y80 w147 h30 +0x200 +Right, Find Tier of Currency:
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, DropDownList, x186 y80 w188, %all_currency%
Gui Font
Gui Font, c0x00e8b2 s10 Bold, Segoe UI
Gui Add, Text, x384 y80 w16 h28 +0x200, ➔
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, Text, x408 y80 w31 h26 +0x200 vFindCurrTier, N/A
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, UpDown, x696 y712 w0 h2  -16, 1
Gui Add, UpDown, x696 y696 w0 h29, 1
Gui Add, Edit, x664 y736 w40 h28, 13
Gui Add, Edit, x664 y696 w41 h28, 13
Gui Font
Gui Font, c0x00e8b2 s10 Bold
Gui Add, GroupBox, x528 y664 w286 h152, Quality and RGB Items
Gui Font
Gui Font, c0x00e8b2 s11, Segoe UI
Gui Add, Edit, x1008 y88 w40 h28, 13

Gui Show, w1144 h839, Window
Return

HandleCurrencyDdlEvent(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {

}

GuiEscape:
GuiClose:
    ExitApp
